### ISSUE TITLE
It throws an error when the given promise has been rejected using toast.loading() method 

### ISSUE THREAD

**Issue by ghost** [walidcherhane/rc-toastr#3]
Thanks for this great library.
There is a **bug** you should be aware of. when I use the `loading()` method if the given promise has been rejected it throws an error that should not be thrown because of using try..catch.
The `error()` callback must be called without any error. 
I believe that you should remove the `throw err` on the last line to fix the bug.
Regards, Javad Moradkhah.

![Annotation 2022-11-21 210422](https://user-images.githubusercontent.com/96623570/203127543-b9c30731-2642-4f7c-a7b7-a2d578345b79.jpg)

**Comment by walidcherhane** [comment]
Hi Javad , Thanks for using rc-toastr and I thank you for reporting this. I will fix that ASAP,
